name: Fetch

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'to fetch'
        required: true
        default: 'https://wrd.ir/'

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Fetch website content
        run: |
          curl -v -L -o output.html "${{ github.event.inputs.url }}"
          echo "Title: $(grep '<title>' output.html | head -1)"
          
      - name: Commit result to repo
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add output.html
          git commit -m "Fetched ${{ github.event.inputs.url }}" || echo "No changes"
          git push
